version: '3.8'

services:
  jupyter:
    build: .
    container_name: ml-worldcup
    ports:
      - "8888:8888"
    volumes:
      # Monta a pasta data/raw para colocar os CSVs sem rebuild
      - ./data:/app/data
      # Monta os notebooks para salvar alterações fora do container
      - ./notebooks:/app/notebooks
    environment:
      - PYTHONUNBUFFERED=1
